# Generated by Django 5.2.3 on 2025-06-22 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
